language: ruby
cache: bundler

script:
  - bundle exec jekyll build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local-dir: ./_site
  name: Deployment Blog
  email: deploy@travis-ci.org
  on:
    branch: master
